### PR TITLE
the scope (parser or lexer) in @parser::header was dropped, so keep t…

### LINKED ISSUE #3877: Parser header is incorrectly inserted in Listener and Visitor files
When adding a `@header` or `@parser::header` to a grammar, the enclosed text block is inserted not only in the generated parser code, but also in the generated listener and visitor code.
This is incorrect because listener and visitor do not contain any production code and as such would never have a need for additional code that is never invoked.

### PR DESCRIPTION
**Pull request by ericvergnaud**
the scope (parser or lexer) in @parser::header was dropped, so keep track of it and only include @header in Listener and Visitor code

Fixes #3877

### CODE REVIEW

**Comment by parrt** [comment]
Based upon your analysis in the bug report, I wonder if we should ever generate header stuff into the listener and visitor files. They can't have any user defined types in there. I'm trying to think of a need for ever injecting header stuff into listener and visitor generated files.

File: tool/src/org/antlr/v4/codegen/model/OutputFile.java [hunk 1]
```diff
@@ -32,10 +33,15 @@ public OutputFile(OutputModelFactory factory, String fileName) {
...
 	public Map<String, Action> buildNamedActions(Grammar g) {
+		return buildNamedActions(g, null);
+	}
+
+	public Map<String, Action> buildNamedActions(Grammar g, Predicate<ActionAST> filter) {
 		Map<String, Action> namedActions = new HashMap<String, Action>();
 		for (String name : g.namedActions.keySet()) {
 			ActionAST ast = g.namedActions.get(name);
-			namedActions.put(name, new Action(factory, ast));
+			if(filter==null || filter.test(ast))
```
Comment (parrt) [inline tool/src/org/antlr/v4/codegen/model/OutputFile.java:43]: I think the project style uses curly braces even if there's only one statement. It reduces one possibility of coding bugs.

File: tool/src/org/antlr/v4/codegen/model/VisitorFile.java [hunk 2]
```diff
@@ -58,7 +58,8 @@ public VisitorFile(OutputModelFactory factory, String fileName) {
 			}
 		}
 		ActionAST ast = g.namedActions.get("header");
-		if ( ast!=null ) header = new Action(factory, ast);
```
Comment (parrt) [inline tool/src/org/antlr/v4/codegen/model/VisitorFile.java:61]: haha looks I or someone else already violated the rules about if statement... I guess it's OK if it's on one line like that.
