### PR TITLE
Preserve line separators for input runtime tests data

### LINKED ISSUE #1098: Incorrect tokens line number for files with '\r' newline.
I have the following grammar:
```ANTLR
lexer grammar T;
ID: [a-z]+;
WS: [ \n] -> skip;
```
And the following input: ```"a" + newLine + "b" + newLine + "c"```

* If newLine is **\r\n**, I got this:
```
[@0,0:0='a',<1>,1:0]
[@1,3:3='b',<1>,2:0]
[@2,6:6='c',<1>,3:0]
[@3,7:6='<EOF>',<-1>,3:1]
```
newLine == **\n**:
```
[@0,0:0='a',<1>,1:0]
[@1,2:2='b',<1>,2:0]
[@2,4:4='c',<1>,3:0]
[@3,5:4='<EOF>',<-1>,3:1]
```
newLine == **\r**:
```
[@0,0:0='a',<1>,1:0]
[@1,2:2='b',<1>,1:2]
[@2,4:4='c',<1>,1:4]
[@3,5:4='<EOF>',<-1>,1:5]
```

In last case line numer for all tokens is 1 and it's wrong. I suggest to support '\r' newLine character. Another variants described at [Wikipedia](https://en.wikipedia.org/wiki/Newline#Representations), but they are too rarely used. Moreover '\r' newline supported by most part of modern editors (IDEA, Visual Studio, Notepad++ etc.).

### PR DESCRIPTION
**Pull request by KvanTTT**

### CODE REVIEW

**Comment by KvanTTT** [comment]
@parrt please review

File: runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java [hunk 1]
```diff
@@ -426,35 +420,39 @@ public static ErrorQueue antlrOnString(String workdir,
...
 
 		List<Pair<String, String>> pairs = new ArrayList<>();
-		String[] lines = dtext.split("\r?\n");
-		for (String line : lines) {
-			if ( line.startsWith("[") && line.length()>2 &&
-				 sections.contains(line.substring(1, line.length() - 1)) ) {
-				if ( currentField!=null ) {
-					pairs.add(new Pair<>(currentField,currentValue));
+
+		Matcher matcher = linePattern.matcher(dtext);
```
Comment (parrt) [inline runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:428]: hiya. not sure i find the complex regex more readable than my simple section detector.

Comment (parrt) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:428]: Reader has to go find and then understand that hairball haha

File: runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java [hunk 2]
```diff
@@ -42,18 +44,10 @@
...
-		"Java",
-		"Node",
-		"PHP",
-		"Python2", "Python3",
-		"Swift"
-	};
+	final static Set<String> sections = new HashSet<>(Arrays.asList(
+		"notes", "type", "grammar", "slaveGrammar", "start", "input", "output", "errors", "flags", "skip"
+	));
+	final static Pattern linePattern = Pattern.compile("([^\\r\\n]*)(\r?\n)");
```
Comment (parrt) [inline runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: to simplify how about a-zA-Z instead of the `^` based one?

File: runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java [hunk 3]
```diff
@@ -426,35 +420,39 @@ public static ErrorQueue antlrOnString(String workdir,
...
+				newSection = sections.contains(sectionName);
+			}
+
+			if (newSection) {
+				if (currentField!=null) {
+					pairs.add(new Pair<>(currentField, currentValue.toString()));
 				}
-				currentField = line.substring(1, line.length() - 1);
-				currentValue = null;
+				preserveSeparator = sectionName.equals("input");
```
Comment (parrt) [inline runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:445]: i see; you needed to upgrade code to handle test files with various line terminators.

File: runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java (hunk 2 above)
Comment (KvanTTT) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: It's not correct, because we have to read files line by line separated by line separators. File content contains different words and chars.

Comment (parrt) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: oh so you see why i don't like regex. i quickly looked and saw `[...]` as matching the section names. haha.  why not split on `\r?\n` then?

Comment (KvanTTT) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: Because in some tests line separators matter. Specifically, in tests in this PR: `LineSeparator_LF.txt eol=lf, LineSeparator_CRLF.txt`. Also, in general, input changing is not good.

Comment (parrt) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: Yeah,I was wondering about that... What about `.*?\r?\n` for the regex?

BTW, do we assume that the same line Terminator is used throughout the entire test descriptor file? I think we should.

Comment (KvanTTT) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: > Yeah,I was wondering about that... What about .*?\r?\n for the regex?

Yes, it's possible to use `(.*?)(\r?\n)` (with groups) but I don't see a big difference. Also, I try to get rid of greedy quantifiers if possible.

> BTW, do we assume that the same line Terminator is used throughout the entire test descriptor file? I think we should.

Line terminator may differ even within one section (it's relevant for input). For other sections line terminator does not matter (and it's being replaced by `\n` because ANTLR uses `\n` for output).

Comment (parrt) [reply runtime-testsuite/test/org/antlr/v4/test/runtime/BaseRuntimeTest.java:50]: Ah, yes, you're right about input/output. Hm..ok, this is close enough. let's go for it.
