### PR TITLE
[C++] Fix Windows min/max macro collision

### LINKED ISSUE #3489: [Cpp Runtime] MSVC: std::min in Guid.cpp needs `NOMINMAX` macro for compilation
I am using the cpp runtime and trying to upgrade the [antlr port in vcpkg](https://github.com/microsoft/vcpkg/tree/master/ports/antlr4) from 4.9.1 to 4.9.3 (see the PR here, https://github.com/microsoft/vcpkg/pull/22438)

My dev and production environment are macOS and Linux, but the vcpkg CI checks run against with Windows environment, and when authoring the vcpkg port for 4.9.3, I found one build failure on Windows. MSVC reports errors like below:
```
[133/300] C:\PROGRA~2\MICROS~3\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   /TP -Dantlr4_shared_EXPORTS -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\atn -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\dfa -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\misc -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\tree -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\tree\pattern -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\tree\xpath /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP    /W4 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /Od /Zi /MP   /W4 /wd4251 -DANTLR4CPP_EXPORTS -MP /wd4251 /showIncludes /Foruntime\CMakeFiles\antlr4_shared.dir\src\support\Guid.cpp.obj /Fdruntime\CMakeFiles\antlr4_shared.dir\ /FS -c D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp
FAILED: runtime/CMakeFiles/antlr4_shared.dir/src/support/Guid.cpp.obj 
C:\PROGRA~2\MICROS~3\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   /TP -Dantlr4_shared_EXPORTS -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\atn -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\dfa -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\misc -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\tree -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\tree\pattern -ID:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\tree\xpath /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP    /W4 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /Od /Zi /MP   /W4 /wd4251 -DANTLR4CPP_EXPORTS -MP /wd4251 /showIncludes /Foruntime\CMakeFiles\antlr4_shared.dir\src\support\Guid.cpp.obj /Fdruntime\CMakeFiles\antlr4_shared.dir\ /FS -c D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
cl : Command line warning D9025 : overriding '/Z7' with '/Zi'
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(75): error C2589: '(': illegal token on right side of '::'
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(75): error C2062: type 'unknown-type' unexpected
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(75): error C2059: syntax error: ')'
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(211): warning C4838: conversion from 'int' to 'const unsigned char' requires a narrowing conversion
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(212): warning C4838: conversion from 'int' to 'const unsigned char' requires a narrowing conversion
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(214): warning C4838: conversion from 'int' to 'const unsigned char' requires a narrowing conversion
D:\buildtrees\antlr4\src\4.9.3-ad469b0542.clean\runtime\src\support\Guid.cpp(215): warning C4838: conversion from 'int' to 'const unsigned char' requires a narrowing conversion
```

It looks like the usage of `std::min` in Guid.cpp makes MSVC unhappy, and MSVC considers "min" as a macro and do some unexpected pre-processing and caused this issue. Currently, I follow the approach [here](https://stackoverflow.com/a/55302808/84540) to define a `NOMINMAX` macro like this to make the vcpkg CI work for Windows MSVC:
```
 #ifdef GUID_WINDOWS
+#define NOMINMAX
 #include <objbase.h>
 #endif
```

But I see other usages of `std::min` in cpp runtime, which doesn't seem to trigger such a compilation error. I am not entirely sure if the current fix in the vcpkg is best (although it seems to work), could any one please suggest what the best approach for fixing this issue? Thanks.

### PR DESCRIPTION
**Pull request by jcking**
Set `WIN32_LEAN_AND_MEAN` and `NOMINMAX` when including a Windows API related header in `support/Guid.cpp`. This resolves #3489. Additionally I updated the macros to be prefixed with `ANTLR4CPP_` which is best practice for public headers.

### CODE REVIEW

**Comment by jcking** [comment]
@mike-lischke

File: runtime/Cpp/runtime/src/support/Guid.h [hunk 1]
```diff
@@ -32,7 +32,9 @@
 #include <string>
 #include <vector>
 
-#ifdef GUID_ANDROID
+#include "antlr4-common.h"
```
Comment (mike-lischke) [inline runtime/Cpp/runtime/src/support/Guid.h:35]: Why's that include necessary here? Builds are usually faster the fewer headers are included.

Comment (jcking) [reply runtime/Cpp/runtime/src/support/Guid.h:35]: If one were to include `support/Guid.h` directly, it would compile incorrectly as the macros would not be defined. This resolves that by always ensuring the macros are defined.

Comment (jcking) [reply runtime/Cpp/runtime/src/support/Guid.h:35]: Another solution is to just move the macros to `support/Guid.h`, I'll leave that to you to decide.

**Review by mike-lischke — APPROVED** [review]
@parrt This patch can be merged.
