### PR TITLE
Check for nonconforming left-recursive rules.

### LINKED ISSUE #822: NullPointerException in bad recursion rule
Error on my part lead to discovering an exception being thrown while generating the grammar.

$ cat error.g4 

```antlr
grammar Error;

a:
  a | b;

b: 'B';
```

$ cat build.xml

```xml
 <project name="error" default="generate">
  <target name="generate" >
                <java classname="org.antlr.v4.Tool" fork="false" failonerror="true">
                        <arg value="-o" />
                        <arg value="java" />
                        <arg value="-package" />
                        <arg value="com.example" />
                        <arg value="-visitor" />
                        <arg value="-Werror" />
                        <arg value="error.g4" />
                        <classpath>
                                <pathelement location="antlr-4.4-complete.jar"/>
                        </classpath>
                </java>
</target>
</project>
```

```
$ ant
build.xml:3: java.lang.NullPointerException
	at org.antlr.v4.tool.Rule.getAltLabels(Rule.java:217)
	at org.antlr.v4.tool.Rule.hasAltSpecificContexts(Rule.java:200)
	at org.antlr.v4.semantics.SymbolChecks.checkForLabelConflicts(SymbolChecks.java:157)
	at org.antlr.v4.semantics.SymbolChecks.process(SymbolChecks.java:105)
	at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:107)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
	at org.antlr.v4.Tool.process(Tool.java:387)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:346)
	at org.antlr.v4.Tool.main(Tool.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:217)
	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:152)
	at org.apache.tools.ant.taskdefs.Java.run(Java.java:771)
	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:221)
	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
```

### LINKED ISSUE #855: Null pointer in named alternative with attributes
Probably the same as https://github.com/antlr/antlr4/issues/822 , this one is stopping my work.
```antlr
grammar probz;
statement
locals[Scope scope]
	: expressionA[$scope] ';'
	;
expressionA[Scope scope]
	: atom[$scope]
	| expressionA[$scope] '[' expressionA[$scope] ']'
	;
atom[Scope scope]
	: 'dummy'
	;
```
Which throws an exception upon compilation:
C:\ANTLRprobz>java -jar antlr4-4.5.1-complete.jar probz.g4
new Rule() name=T__0 ast=RULE
new Rule() name=T__1 ast=RULE
new Rule() name=T__2 ast=RULE
new Rule() name=T__3 ast=RULE
getAltLabels() index=0 numberOfAlts=1 name=T__0 alt[i1].Num1.ast=ALT=>true
getAltLabels() index=1 numberOfAlts=1 name=T__1 alt[i1].Num1.ast=ALT=>true
getAltLabels() index=2 numberOfAlts=1 name=T__2 alt[i1].Num1.ast=ALT=>true
getAltLabels() index=3 numberOfAlts=1 name=T__3 alt[i1].Num1.ast=ALT=>true
new Rule() name=statement ast=RULE
new Rule() name=expressionA ast=RULE
new Rule() name=atom ast=RULE
getAltLabels() index=0 numberOfAlts=1 name=statement alt[i1].Num1.ast=ALT=>true
getAltLabels() index=1 numberOfAlts=1 name=expressionA alt[i1].Num1.ast=ALT=>true
getAltLabels() index=1 numberOfAlts=1 name=expressionA alt[i1].Num1.ast=ALT=>true
getAltLabels() index=2 numberOfAlts=1 name=atom alt[i1].Num1.ast=null=>true
context [/report INTERNAL_ERROR] 1:17 attribute arg isn't defined
error(20):  internal error:
Exception in thread "main" java.lang.NullPointerException
        at org.antlr.v4.semantics.SemanticPipeline.process(SemanticPipeline.java:116)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:399)
        at org.antlr.v4.Tool.process(Tool.java:386)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:345)
        at org.antlr.v4.Tool.main(Tool.java:192)

### PR DESCRIPTION
**Pull request by parrt**
We didn't check for left-recursive rules that didn't follow pattern that would lead to error. added unit tests. Passes all tests. Fixes #822, Fixes #855.

### CODE REVIEW

File: tool/src/org/antlr/v4/tool/ErrorType.java [hunk 1]
```diff
@@ -956,6 +956,8 @@
 	 */
 	CHANNELS_BLOCK_IN_COMBINED_GRAMMAR(164, "custom channels are not supported in combined grammars", ErrorSeverity.ERROR),
 
+	NONCONFORMING_LR_RULE(165, "rule <arg> is left recursive but doesn't conform to a pattern ANTLR can handle", ErrorSeverity.ERROR),
```
Comment (sharwell) [inline tool/src/org/antlr/v4/tool/ErrorType.java]: This error number conflicts with the error numbers in #697. Since those error codes shipped in the 4.4 release of the optimized fork, it would be helpful if `NONCONFORMING_LR_RULE` was renumbered as error 169 (leaving space for 165 through 168 to be added to this project when #697 is ready).

Comment (parrt) [inline tool/src/org/antlr/v4/tool/ErrorType.java]: oh sure.  it would be nice to renumber everything but it would  break all of the error numbers if people rely on them; I'm sure no one is relying on them but we might as well keep backward compatibility here. ok, so 169 it is.
