### PR TITLE
Fixes #1556.

### LINKED ISSUE #1556: crash upon bad grammar
Grammar from https://github.com/antlr/intellij-plugin-v4/issues/290 crashes antlr:

```
beast:/tmp $ a4.6 PowerBasic.g4 
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 1426:63 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from after line 1426:63 mismatched tree node: ALT expecting <UP>
error(20): PowerBasic.g4:18:14: internal error: Rule perfectSyncCommands undefined 
error(20):  internal error: element list has first|last == null 
Exception in thread "main" java.lang.NullPointerException
	at org.antlr.v4.automata.ParserATNFactory.elemList(ParserATNFactory.java:481)
	at org.antlr.v4.automata.ParserATNFactory.alt(ParserATNFactory.java:450)
	at org.antlr.v4.parse.ATNBuilder.alternative(ATNBuilder.java:557)
	at org.antlr.v4.parse.ATNBuilder.ruleBlock(ATNBuilder.java:291)
	at org.antlr.v4.automata.ParserATNFactory._createATN(ParserATNFactory.java:161)
	at org.antlr.v4.automata.ParserATNFactory.createATN(ParserATNFactory.java:108)
	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:389)
	at org.antlr.v4.Tool.process(Tool.java:362)
	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
	at org.antlr.v4.Tool.main(Tool.java:168)
```

### PR DESCRIPTION
**Pull request by parrt**
```
beast:/tmp $ a4.6 T.g4
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
org/antlr/v4/parse/GrammarTreeVisitor.g: node from line 2:7 no viable alternative at input '..'
context [/report INTERNAL_ERROR] 1:17 attribute arg isn't defined
error(20):  internal error:
beast:/tmp $ a4.6.1 T.g4
error(181): T.g4:2:4: token ranges not allowed in parser: 'A'..'Z'
```

### CODE REVIEW

File: tool/src/org/antlr/v4/tool/ErrorType.java [hunk 1]
```diff
@@ -1045,6 +1045,21 @@
...
+	 * are not ordered (except in implementation).
+	 * </p>
+	 *
+	 * <pre>
+	 * grammar T;
+	 * a : 'A'..'Z' ;
+	 * </pre>
+	 *
+	 */
+	TOKEN_RANGE_IN_PARSER(181, "token ranges not allowed in parser: <arg>..<arg2>", ErrorSeverity.ERROR),
```
Comment (parrt) [inline tool/src/org/antlr/v4/tool/ErrorType.java]: @sharwell any issues with 181 in your fork?

Comment (sharwell) [inline tool/src/org/antlr/v4/tool/ErrorType.java]: Nope!
