### PR TITLE
Use signed ints for ATN serialization not uint16, except for java

### LINKED ISSUE #840: Getting this error: Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element out of range
I'm using last version pulled out from git (4.5.1) and built under OSx Yosemite, tryed both with jdk6 and jdk7 but with my file, which is: https://gist.github.com/agiovacchini/52cc6dc9210a65dfc659#file-example-g4 I get this error:

Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element out of range
    at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:384)
    at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:563)
    at org.antlr.v4.codegen.model.SerializedATN.<init>(SerializedATN.java:46)
    at org.antlr.v4.codegen.model.Recognizer.<init>(Recognizer.java:87)
    at org.antlr.v4.codegen.model.Lexer.<init>(Lexer.java:51)
    at org.antlr.v4.codegen.OutputModelController.lexer(OutputModelController.java:176)
    at org.antlr.v4.codegen.OutputModelController.buildLexerOutputModel(OutputModelController.java:129)
    at org.antlr.v4.codegen.CodeGenerator.generateLexer(CodeGenerator.java:142)
    at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:73)
    at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:428)
    at org.antlr.v4.Tool.process(Tool.java:378)
    at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:345)
    at org.antlr.v4.Tool.main(Tool.java:192)

The launch script is like this:
# !/bin/zsh

export CLASSPATH=".:./antlr4/dist/antlr4-4.5.1-complete.jar"
alias antlr4='java -jar ./antlr4/dist/antlr4-4.5.1-complete.jar'
alias grun='java org.antlr.v4.runtime.misc.TestRig'
antlr4 example.g4

### LINKED ISSUE #1863: Add a more understandable message than "Serialized ATN data element .... element ... out of range 0..65535"
Hi,

I tried to build a big grammar file with antlr4. I've  got the following message when I execute the ANTLR  code that generate java source : 
```
Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element ```
101246 element 11 out of range 0..65535
        at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:361)
        at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
        at org.antlr.v4.codegen.model.SerializedATN.<init>(SerializedATN.java:22)
        at org.antlr.v4.codegen.model.Recognizer.<init>(Recognizer.java:64)
        at org.antlr.v4.codegen.model.Lexer.<init>(Lexer.java:27)
        at org.antlr.v4.codegen.OutputModelController.lexer(OutputModelController.java:151)
        at org.antlr.v4.codegen.OutputModelController.buildLexerOutputModel(OutputModelController.java:104)
        at org.antlr.v4.codegen.CodeGenerator.generateLexer(CodeGenerator.java:119)
        at org.antlr.v4.codegen.CodeGenPipeline.process(CodeGenPipeline.java:54)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:404)
        at org.antlr.v4.Tool.process(Tool.java:354)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:321)
        at org.antlr.v4.Tool.main(Tool.java:168)
```

From what I understand, my grammar file is too long.

Is that possible to get a message to explain that the limitation of the library is reached ?

For your test, here it is my grammar file ( a bit cryptic cause I anonymize it) :
https://gist.github.com/jbarotin/7f7caf419b9038c2a548969265788392

### LINKED ISSUE #2732: UnsupportedOperationException while generating code for large grammars.
When generating code for large grammars we are getting this exception log. The code generation targets C#.

Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element 85257 element 11 out of range 0..65535
  	at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:362)
  	at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
  	at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
  	at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
  	at org.antlr.v4.Tool.process(Tool.java:361)
  	at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
  	at org.antlr.v4.Tool.main(Tool.java:172)
  
  
  UserGrammar.g4

### LINKED ISSUE #3338: Serialized ATN data element 810567 element 11 out of range 0..65535
I have a `.g4` file in which one of the syntax rules has more than 80,000 alternatives,
when I run `antlr4 -Dlanguage=Go -visitor`
below exception occured

```
Exception in thread "main" java.lang.UnsupportedOperationException: Serialized ATN data element 810567 element 11 out of range 0..65535
        at org.antlr.v4.runtime.atn.ATNSerializer.serialize(ATNSerializer.java:361)
        at org.antlr.v4.runtime.atn.ATNSerializer.getSerialized(ATNSerializer.java:601)
        at org.antlr.v4.Tool.generateInterpreterData(Tool.java:745)
        at org.antlr.v4.Tool.processNonCombinedGrammar(Tool.java:400)
        at org.antlr.v4.Tool.process(Tool.java:361)
        at org.antlr.v4.Tool.processGrammarsOnCommandLine(Tool.java:328)
        at org.antlr.v4.Tool.main(Tool.java:172)
```

### LINKED ISSUE #3592: do we need this C++ ATN serialization?
Hi @mike-lischke and @jcking I think only the ANTLR tool itself needs the ATN serialization; the targets only need deserialization.  can we get rid of this file?

https://github.com/antlr/antlr4/blob/dev/runtime/Cpp/runtime/src/atn/ATNSerializer.cpp

### PR DESCRIPTION
**Pull request by parrt**
Resolves https://github.com/antlr/antlr4/discussions/3580

Fixes #3592

* fixes #1863
* fixes #2732
* fixes #3338
* fixes #840

JavaScript, Java, Go do NOT work for big ATN with state nums > 65535. Not sure why; actually I think it's just that they take forever.   also there seems to be an out of memory error when tested using CI, so I have disabled our big grammar test for all but java and C++ targets, which seemed to work fine.

### CODE REVIEW

**Comment by parrt** [comment]
This is damn close to being ready. I think tests will all pass. All I had to do was convert the C++ and go targets to use int not unint16.  changed a few method names to be consisted.  then removed -1 -> 0xFFFF conversion during serialization for everybody but java. refactored a bungees to make it nicer code. we'll start to add @KvanTTT tests now by cherrypicking.

**Review by mike-lischke — CHANGES_REQUESTED** [review]

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java [hunk 1]
```diff
@@ -286,86 +280,129 @@ public void serializeCodePoint(IntegerList data, int cp) {
...
 		}
+	}
 
-		int ndecisions = atn.decisionToState.size();
-		data.add(ndecisions);
-		for (DecisionState decStartState : atn.decisionToState) {
-			data.add(decStartState.stateNumber);
+	private Map<IntervalSet, Integer> addSets() {
+		List<IntervalSet> bmpSets = new ArrayList<>();
+		List<IntervalSet> smpSets = new ArrayList<>();
```
Comment (KvanTTT) [inline runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:287]: These code becomes useless since all integers becomes 32-bit. It should be simplified (no distinguish between bmd and smp sets).

File: runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp [hunk 2]
```diff
@@ -221,28 +221,27 @@ namespace {
     return s;
   }
 
-  uint32_t deserializeInt32(const std::vector<uint16_t>& data, size_t offset) {
+  uint32_t deserializeInt32(const std::vector<int>& data, size_t offset) {
     return static_cast<uint32_t>(data[offset]) | (static_cast<uint32_t>(data[offset + 1]) << 16);
   }
 
-  ssize_t readUnicodeInt(const std::vector<uint16_t>& data, int& p) {
+  ssize_t readInt16(const std::vector<int>& data, int& p) {
```
Comment (KvanTTT) [inline runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp:228]: Should be removed since all integers are Int32.

File: runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp [hunk 3]
```diff
@@ -221,28 +221,27 @@ namespace {
...
-  ssize_t readUnicodeInt32(const std::vector<uint16_t>& data, int& p) {
+  ssize_t readInt32(const std::vector<int>& data, int& p) {
     auto result = deserializeInt32(data, p);
     p += 2;
     return static_cast<ssize_t>(result);
   }
 
   // We templatize this on the function type so the optimizer can inline
-  // the 16- or 32-bit readUnicodeInt/readUnicodeInt32 as needed.
+  // the 16- or 32-bit readInt16/readInt32 as needed.
```
Comment (KvanTTT) [inline runtime/Cpp/runtime/src/atn/ATNDeserializer.cpp:239]: Update comment.

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java [hunk 4]
```diff
@@ -597,4 +634,11 @@ private void serializeInt(IntegerList data, int value) {
 		data.add((char)value);
 		data.add((char)(value >> 16));
 	}
+
+	private int encodeInt(int v) {
+		if ( language.equals("Java") && v==-1 ) {
+			return 0xFFFF;
```
Comment (KvanTTT) [inline runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:640]: It looks incorrect since all int values have direct mapping. For Java Int32 encoding should be implemented as well.

File: tool/src/org/antlr/v4/codegen/model/SerializedJavaATN.java [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+import org.antlr.v4.runtime.atn.ATN;
+import org.antlr.v4.runtime.atn.ATNSerializer;
+import org.antlr.v4.runtime.misc.IntegerList;
+
+/** A serialized ATN for the java target, which requires we use strings and 16-bit unicode values */
+public class SerializedJavaATN extends SerializedATN {
+	private final String[] serializedAsString;
+	private final String[][] segments;
+
+	public SerializedJavaATN(OutputModelFactory factory, ATN atn) {
```
Comment (KvanTTT) [inline tool/src/org/antlr/v4/codegen/model/SerializedJavaATN.java:14]: I suggest using universal class for SerializedATN. Is it possible to use `Object[]` array both for `String[]` and for `Integer[]`?

If not it probably makes sense to rename the classes to `SerializedATNByInt` and `SerializedATNByString`.

**Review by KvanTTT — COMMENTED** [review]
* I suggest implementing universal 32-bit encoding that includes Java as well (you can leave it to me)
* smp and bmp sets become useless with 32-bit encoding

File: runtime/Cpp/runtime/src/Parser.cpp [hunk 6]
```diff
@@ -38,7 +38,7 @@ struct BypassAltsAtnCache final {
   /// bypass alternatives.
   ///
   /// <seealso cref= ATNDeserializationOptions#isGenerateRuleBypassTransitions() </seealso>
-  std::map<std::vector<uint16_t>, std::unique_ptr<const atn::ATN>> map;
+  std::map<std::vector<int>, std::unique_ptr<const atn::ATN>> map;
```
[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Cpp/runtime/src/Parser.cpp:41]: I started wondering about that the minute I hit commit, dang it.  we might as well be explicit and make it int32_t, I'll redo that.

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java (hunk 1 above)
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:287]: yep! That's next on my list.

File: runtime/Cpp/runtime/src/Parser.cpp (hunk 6 above)
[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Cpp/runtime/src/Parser.cpp]: done

File: runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp [hunk 7]
```diff
@@ -61,8 +61,8 @@ void xpathLexerInitialize() {
       "STRING"
     }
   );
-  static const int serializedATNSegment0[] = {
-    0x4, 0x0, 0x8, 0x32, 0x6, -1, 0x2, 0x0, 0x7, 0x0, 0x2, 0x1, 0x7,
+  static const int32_t serializedATNSegment0[] = {
+    0x4, 0x0, 0x8, 0x32, 0x6, 0xffff, 0x2, 0x0, 0x7, 0x0, 0x2, 0x1, 0x7,
```
Comment (mike-lischke) [inline runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp:65]: You forgot to keep the -1.

File: runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp [hunk 8]
```diff
@@ -75,7 +75,7 @@ void xpathLexerInitialize() {
        0x0, 0x2, 0x5, 0x0, 0x30, 0x39, 0x5f, 0x5f, 0xb7, 0xb7, 0x300, 0x36f,
        0x203f, 0x2040, 0xd, 0x0, 0x41, 0x5a, 0x61, 0x7a, 0xc0, 0xd6, 0xd8,
        0xf6, 0xf8, 0x2ff, 0x370, 0x37d, 0x37f, 0x1fff, 0x200c, 0x200d, 0x2070,
-       0x218f, 0x2c00, 0x2fef, 0x3001, 0xd7ff, 0xf900, 0xfdcf, 0xfdf0, -1,
+       0x218f, 0x2c00, 0x2fef, 0x3001, 0xd7ff, 0xf900, 0xfdcf, 0xfdf0, 0xffff,
```
Comment (mike-lischke) [inline runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp:78]: same here

**Review by mike-lischke — CHANGES_REQUESTED** [review]

File: runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp (hunk 7 above)
Comment (parrt) [reply runtime/Cpp/runtime/src/tree/xpath/XPathLexer.cpp:65]: oops. thanks.

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java (hunk 1 above)
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:305]: ok, I think i've pushed all 32-bit stuff minus Java target.  All sets are 32-bit ranges not 16 and 32 (bmp,smp).

File: tool/src/org/antlr/v4/codegen/model/SerializedJavaATN.java (hunk 5 above)
Comment (parrt) [reply tool/src/org/antlr/v4/codegen/model/SerializedJavaATN.java:14]: yeah, I wasn't sure about this one but given that it's a very different encoding it's probably ok to have separate objects in the model because that leads to a separate output template.

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java (hunk 4 above)
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:658]: Yeah,I will think about the Java target once I get everybody else pure int.   most of the targets seemed to work with 32-bit ATN state numbers, but the unit tests ran out of memory running the big lexer via CI. also some of the targets don't work and I wasn't sure why.  I was going to make a separate issue to collect all of the thirty two bit atn state stuff that can then work off of this completed PR when merged.

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java [hunk 9]
```diff
@@ -65,141 +75,116 @@ public ATNSerializer(ATN atn, List<String> tokenNames) {
...
+				int value = data.get(i);
+				if (value < Character.MIN_VALUE || value > Character.MAX_VALUE) {
+					throw new UnsupportedOperationException("Serialized ATN data element " +
+							value + " element " + i + " out of range " + (int) Character.MIN_VALUE + ".." + (int) Character.MAX_VALUE);
+				}
+
+				// Shift by 2, to avoid inefficient modified utf-8 and coding done by java class files
+				data.set(i, (value + 2) & 0xFFFF);
+			}
+		}
```
Comment (KvanTTT) [inline runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:107]: Can we move this transform to `SerializedATN`? Remove range check and split 32-bit integers on two 16-bit during writing. Especially considering now we have `SerializedATN` and `SerializedJavaATN`.

Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNSerializer.java:107]: We must think alike because I tried that yesterday and gave up when I couldn't immediately get the deserialization tests working. haha.  I'm going to try again today because it is a good idea to separate this.  I will also try a quick combined 16+32 encoding for java following your ideas.

**Comment by parrt** [comment]
Just pushed a huge refactoring and cleanup with comments etcetera; thanks to @KvanTTT  for pointing the way in many of the improvement.  I have moved the bump by 2 and -1 -> FFFF to the actual stringification part.  the only thing left is to deal with 32-bit char/states.  let's see if the tests pass. I think they work locally

File: tool-testsuite/test/org/antlr/v4/test/tool/ATNDescriber.java [hunk 10]
```diff
@@ -0,0 +1,203 @@
...
+ * rule 0:1 1
+ * mode 0:0
+ * 0:'a'..128169
+ * 0->1 EPSILON 0,0,0
+ * 1->3 EPSILON 0,0,0
+ * 3->4 SET 0,0,0
+ * 4->2 EPSILON 0,0,0
+ * 0:0
+ */
+public class ATNDescriber {
```
Comment (KvanTTT) [inline tool-testsuite/test/org/antlr/v4/test/tool/ATNDescriber.java:26]: Great! It looks similar to improvements in one of my PR: https://github.com/antlr/antlr4/pull/3556

File: runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LexerExec/UnicodeCharSet.txt [hunk 11]
```diff
@@ -6,7 +6,7 @@ Lexer
 
 [grammar]
 lexer grammar L;
-ID : ([A-Z_]|'Ā'..'￾') ([A-Z_0-9]|'Ā'..'￾')*;
+ID : ([A-Z_]|'Ā'..'\uFFFC') ([A-Z_0-9]|'Ā'..'\uFFFC')*; // FFFD+ are not valid char
```
[the remark this answers is not in the document]
Comment (parrt) [reply runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LexerExec/UnicodeCharSet.txt:9]: \FFFD+ aren't valid char though. I suppose someone could be parsing 16 bit unsigned char?

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java [hunk 12]
```diff
@@ -83,48 +45,49 @@ public ATNDeserializer(ATNDeserializationOptions deserializationOptions) {
...
+//		for (int i = 1; i < data.length; i++) {
+//			dataI[i] = data[i] - 2;
+//		}
+		return deserialize(decodeIntsEncodedAs16BitWords(data));
+	}
 
+	public ATN deserialize(int[] data) {
 		int p = 0;
-		int version = toInt(data[p++]);
+		int version = data[p++];
```
[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java:53]: Possibly. It's a bit more verbose and current thing works.

```
		class ATNReader {
			private int p = 0;
			int read() { return data[p++]; }
		}
		ATNReader reader = new ATNReader();
		int version = reader.read();
...
```

[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java:53]: (`data` is an arg not a field of ATNDeserializer.)

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java [hunk 13]
```diff
@@ -643,4 +592,78 @@ protected LexerAction lexerActionFactory(LexerActionType type, int data1, int da
...
+	public static IntegerList encodeIntsWith16BitWords(IntegerList data) {
+		IntegerList data16 = new IntegerList((int)(data.size()*1.5));
+		for (int i = 0; i < data.size(); i++) {
+			int v = data.get(i);
+			if ( v==-1 ) { // use two max uint16 for -1
+				data16.add(0xFFFF);
+				data16.add(0xFFFF);
+			}
+			else if (v <= 0x7FFF) {
+				data16.add((char)v);
```
[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java:615]: yeah i guess you're right. thanks.

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java [hunk 14]
```diff
@@ -643,4 +592,78 @@ protected LexerAction lexerActionFactory(LexerActionType type, int data1, int da
...
+			else { // hi bit set. Implies 2-word value
+				char vnext = data16[i+1];
+				if ( v==0xFFFF && vnext == 0xFFFF ) { // is it -1?
+					data[i2++] = -1;
+				}
+				else { // 31-bit int
+					data[i2++] = (v & 0x7FFF) << 16 | (vnext & 0xFFFF);
+				}
+				i += 2;
+			}
```
[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java:656]: Good one. yes.

File: tool-testsuite/test/org/antlr/v4/test/tool/ATNDescriber.java (hunk 10 above)
Comment (parrt) [reply tool-testsuite/test/org/antlr/v4/test/tool/ATNDescriber.java:26]: woohoo!

File: runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java [hunk 15]
```diff
@@ -643,4 +592,78 @@ protected LexerAction lexerActionFactory(LexerActionType type, int data1, int da
 			throw new IllegalArgumentException(String.format(Locale.getDefault(), "The specified lexer action type %s is not valid.", type));
 		}
 	}
+
+	/** Given a list of integers representing a serialized ATN, encode values too large to fit into 15 bits
+	 *  as two 16bit values. We use the high bit (0x8000_0000) to indicate values requiring two 16 bit words.
+	 *  If the high bit is set, we grab the next value and combine them to get a 31-bit value. The possible
+	 *  input int values are [-1,0x7FFF_FFFF].
+	 *
+	 * 		| compression/encoding                         | bytes count | type            |
```
[the remark this answers is not in the document]
Comment (parrt) [reply runtime/Java/src/org/antlr/v4/runtime/atn/ATNDeserializer.java:595]: oh right. thanks.

File: runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LexerExec/UnicodeCharSet.txt (hunk 11 above)
[the remark this answers is not in the document]
Comment (parrt) [reply runtime-testsuite/resources/org/antlr/v4/test/runtime/descriptors/LexerExec/UnicodeCharSet.txt:9]: the other problem is we cannot allow `\uFFFF` as that is still special since the high bit is set. it means that the next 16bit word contains the remainder of the 32bit value. I think I'm ok requiring that binary parses in bytes and characters use valid characters.

**Comment by parrt** [comment]
woot! merged.

**Comment by mike-lischke** [comment]
Looks like you got more time to work on ANTLR4, since you joined Google ;-)
