### PR TITLE
Fix multiple problems with optional block bypass at end of rule

### LINKED ISSUE #1545: Parentheses without quantifier in parser rule lead to syntax error on non-root rule parsing
Consider the following grammar:

```ANTLR
grammar OpenDeviceStatement;

program : statement+ '.' ;

statement : 'OPEN' ( 'DEVICE' (  OPT1  |  OPT2  |  OPT3  )? )+ ;

//statement : 'OPEN' ( 'DEVICE' ( (OPT1) |  OPT2  |  OPT3  )? )+ ;
//statement : 'OPEN' ( 'DEVICE' (  OPT1  | (OPT2) |  OPT3  )? )+ ;
//statement : 'OPEN' ( 'DEVICE' (  OPT1  |  OPT2  | (OPT3) )? )+ ;
//statement : 'OPEN' ( 'DEVICE' ( (OPT1) | (OPT2) |  OPT3  )? )+ ;
//statement : 'OPEN' ( 'DEVICE' ( (OPT1) |  OPT2  | (OPT3) )? )+ ;
//statement : 'OPEN' ( 'DEVICE' (  OPT1  | (OPT2) | (OPT3) )? )+ ;
//statement : 'OPEN' ( 'DEVICE' ( (OPT1) | (OPT2) | (OPT3) )? )+ ;

OPT1 : 'OPT-1';
OPT2 : 'OPT-2';
OPT3 : 'OPT-3';

WS : (' '|'\n')+ -> channel(HIDDEN);

```

When parsing the text ```OPEN DEVICE DEVICE``` (directly through ```statement()```, and **not** through ```program()```) everything works fine.

Trace output:
```
enter   statement, LT(1)=OPEN
consume [@0,0:3='OPEN',<2>,1:0] rule statement
consume [@2,5:10='DEVICE',<3>,1:5] rule statement
consume [@4,12:17='DEVICE',<3>,1:12] rule statement
exit    statement, LT(1)=<EOF>
```

Tree output:
```
(statement OPEN DEVICE DEVICE)
```

### Exercise 1

Now consider substituting any of the alternative ```statement``` definitions (where one or more ```OPTx``` tokens are parenthized).

Tree output is still the same. But now some ```syntaxError()``` get reported on the ```ANTLRErrorListener```. Here the trace along with ```ConsoleErrorListener``` output:

```
enter   statement, LT(1)=OPEN
consume [@0,0:3='OPEN',<2>,1:0] rule statement
consume [@2,5:10='DEVICE',<3>,1:5] rule statement
consume [@4,12:17='DEVICE',<3>,1:12] rule statement
line 1:18 no viable alternative at input '<EOF>'
exit    statement, LT(1)=<EOF>
```

Maybe ANTLR4 is expecting either: any ```OPTx``` (an optional argument to the previous ```DEVICE```), another ```DEVICE```, ```OPEN``` (for a new ```statement```) or ```.``` (period, to close the ```program```). I understand that ```<EOF>``` is not to be expected if we were to parse the text from the root rule ```program``` (here I just assume that ANTLR4 breaks its promise to be able to parse from any rule, giving no rule the special quality of being *the root rule* or *the main rule*).

### Exercise 2 (on top of exercise 1)

Going one step further, lets then parse the text ```OPEN DEVICE DEVICE.``` (notice the period). Again our parsing starts at ```statement``` rule.

What trace do we get?

```
enter   statement, LT(1)=OPEN
consume [@0,0:3='OPEN',<2>,1:0] rule statement
consume [@2,5:10='DEVICE',<3>,1:5] rule statement
consume [@4,12:17='DEVICE',<3>,1:12] rule statement
line 1:18 extraneous input '.' expecting {<EOF>, 'DEVICE', 'OPT-1', 'OPT-2', 'OPT-3'}
line 1:19 no viable alternative at input '<EOF>'
exit    statement, LT(1)=<EOF>
```

Weirdly it **is** expecting ```<EOF>``` (and not ```OPEN``` nor ```.``` because they are outside ```statement``` rule).

The output tree wrongly incorporates the ```.```: 
```
(statement OPEN DEVICE DEVICE .)
```
(well, at least I expected it to stop at the second ```DEVICE```, leaving the ```.``` unparsed)

--------------------------------------------------------------------------------
I think there are 3 bugs here:
1. the superfluous parentheses around ```OPTx``` should have no effect in the generated parser;
2. the parsing through the non-root rule ```statement``` should not see the ```<EOF>``` as unexpected (after ```DEVICE``` or any ```OPTx``` token);
3. the parsing through the non-root rule ```statement``` should not consume the ```.``` token (not sure about this one; this may only apply to lexers, not to parsers).

What do you think?

### PR DESCRIPTION
**Pull request by sharwell**
* Add tests for scenarios presented in the original bug
* Fix `DefaultErrorStrategy.sync` not handling falling off decision rule the same way as `adaptivePredict`
* Fix code generation for `LL1OptionalBlock`

Fixes #1545

### CODE REVIEW

File: runtime/Swift/Antlr4/org/antlr/v4/runtime/DefaultErrorStrategy.swift [hunk 1]
```diff
@@ -226,7 +226,11 @@ public class DefaultErrorStrategy: ANTLRErrorStrategy {
         // try cheaper subset first; might get lucky. seems to shave a wee bit off
         //let set : IntervalSet = recognizer.getATN().nextTokens(s)
 
-        if try recognizer.getATN().nextTokens(s).contains(la) || la == CommonToken.EOF {
+        if try recognizer.getATN().nextTokens(s).contains(CommonToken.EPSILON) {
```
Comment (sharwell) [inline runtime/Swift/Antlr4/org/antlr/v4/runtime/DefaultErrorStrategy.swift]: ⚠️ This is sub-optimal but should work fine. Someone familiar with the Swift syntax should reply with a comment indicating how to cache the result of `nextTokens` in a local variable like I've done for each of the other targets.

**Comment by parrt** [comment]
@sharwell looks like some tests are failing. I'll try to look soon.

File: runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java [hunk 2]
```diff
@@ -414,7 +414,7 @@
 
 		/**
 		 grammar T;
-		 a : 'a' 'b'* ;
+		 a : 'a' 'b'* EOF ;
```
Comment (sharwell) [inline runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java]: :memo: The original behavior of the test was retained by ensuring the `'b'*` loop didn't look all the way to the end of `a`.

File: runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java [hunk 3]
```diff
@@ -436,7 +436,7 @@
 
 		/**
 		 grammar T;
-		 a : 'a' ('b'|'z'{<Pass()>})*;
+		 a : 'a' ('b'|'z'{<Pass()>})* EOF ;
```
Comment (sharwell) [inline runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java]: :memo: The original behavior of the test was retained by ensuring the closure loop didn't look all the way to the end of `a`.

File: runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java [hunk 4]
```diff
@@ -135,7 +135,7 @@
 	public static class InvalidEmptyInput extends BaseParserTestDescriptor {
 		public String input = "";
 		public String output = null;
-		public String errors = "line 1:0 missing ID at '<EOF>'\n";
+		public String errors = "line 1:0 mismatched input '<EOF>' expecting ID\n";
```
Comment (sharwell) [inline runtime-testsuite/test/org/antlr/v4/test/runtime/descriptors/ParserErrorsDescriptors.java]: @parrt This behavior change was caused by removing the `la == TokenConstants.EOF` check in `DefaultErrorStrategy.sync`. Do you have a preference regarding the handling?

**Comment by parrt** [comment]
Thanks @sharwell !
