### PR TITLE
ANTLR generates a wrong lexer code if type, channel or mode commands use inproper identifier

### LINKED ISSUE #1411: ANTLR generates a wrong lexer code if type, channel or mode commands use inproper identifier
Consider the following simple grammar:

```ANTLR
lexer grammar WrongIdInCommandsLexer;

tokens { TOKEN1 }
channels { CHANNEL1 }

TOKEN: 'asdf'  -> type(CHANNEL1), channel(MODE1), mode(TOKEN1);

mode MODE1;

MODE1_TOKEN: 'bbbb';
```

### Actual behavior

ANTLR generates inproper lexer which throws an NRE exception during parsing process (C# Sharwell runtime).

### Expected behavior

ANTLR should show 3 errors about wrong type, channel and mode identifiers in respective commands and should not generate inproper lexer.

### PR DESCRIPTION
**Pull request by KvanTTT**
Fixes #1411
* `getConstantValue` replaced with `getModeConstantValue`, `getTokenConstantValue `and `getChannelConstantValue `methods.
* Added new unit-test.
* ErrorType simplified, tests fixed.

### CODE REVIEW

File: tool/src/org/antlr/v4/tool/ErrorType.java [hunk 1]
```diff
@@ -960,57 +960,21 @@
...
-	 *
-	 * <p>empty strings not allowed</p>
+	 * <p>string literals cannot be empty</p>
 	 *
 	 * <pre>A: '''test''';</pre>
 	 * <pre>B: '';</pre>
 	 * <pre>C: 'test' '';</pre>
 	 */
-	EMPTY_STRINGS_NOT_ALLOWED(174, "string literals cannot be empty", ErrorSeverity.ERROR),
+	EMPTY_STRINGS_NOT_ALLOWED(171, "string literals cannot be empty", ErrorSeverity.ERROR),
```
Comment (sharwell) [inline tool/src/org/antlr/v4/tool/ErrorType.java]: ❗️ Renumbering an existing error or warning is not an allowed change. After a warning or error is introduced, that number can never be used for any other purpose. See `ALL_OPS_NEED_SAME_ASSOC` and `LEXER_ACTION_PLACEMENT_ISSUE` for examples of old error numbers that are no longer reported by ANTLR 4.

File: tool/src/org/antlr/v4/automata/LexerATNFactory.java [hunk 2]
```diff
@@ -412,8 +412,7 @@ else if ("popMode".equals(command) && arg == null) {
 		}
 		else if ("mode".equals(command) && arg != null) {
 			String modeName = arg.getText();
-			checkMode(modeName, arg.token);
-			Integer mode = getConstantValue(modeName, arg.getToken());
+			Integer mode = getModeConstantValue(modeName, arg.getToken());
```
Comment (KvanTTT) [inline tool/src/org/antlr/v4/automata/LexerATNFactory.java]: 1. Ok, I'll revert old error types and numbers.
2. Ok, I'll revert old message format for such errors.

**Comment by parrt** [comment]
@sharwell is this one cool now?

**Comment by KvanTTT** [comment]
@parrt please give feedback for issue https://github.com/antlr/antlr4/issues/1411#issuecomment-263614417 at first.

**Comment by parrt** [comment]
Thanks @KvanTTT !!
