### PR TITLE
All error codes distinct

### LINKED ISSUE #1865: Duplicate error codes
In file [ErrorType.java](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/tool/ErrorType.java) there are 2 errors using the same error code 160, which is wrong. The first occurence also appears out of order, so I guess this a copy/paste problem and the error number should be 114 or so.

### PR DESCRIPTION
**Pull request by KvanTTT**
fixes #1865

### CODE REVIEW

File: tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java [hunk 1]
```diff
@@ -60,6 +61,16 @@ public void testSetUp() throws Exception {
 		super.testSetUp();
 	}
 
+	@Test
+	public void AllErrorCodesDistinct() {
+		ErrorType[] errorTypes = ErrorType.class.getEnumConstants();
+		for (int i = 0; i < errorTypes.length; i++) {
```
Comment (parrt) [inline tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java]: maybe add error types to a set then compare length of the set and the number of error types?

Comment (KvanTTT) [inline tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java]: Ok, will fix it.

Comment (KvanTTT) [inline tool-testsuite/test/org/antlr/v4/test/tool/TestToolSyntaxErrors.java]: I think my solution is better because of `assertNotEquals` fails on the certain error code. It's more clear that length comparison.
