### PR TITLE
[Dart] Support Dart multiple platforms.

### LINKED ISSUE #3190: Flutter/Dart web support
First of all, great job with the current dart runtime and the quick nullable release that you did in the last weeks. 👍🏽 

We are using antlr4 in our flutter app which will run on the web soon. The current antlr4 dart runtime is not able to compile to js. 
Here is the output when compiling the flutter web project:

```
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:31:16: Error: The integer literal 0x5555555555555555 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x5555555555555400 is the nearest value that can be represented exactly.
    const m1 = 0x5555555555555555;
               ^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:32:16: Error: The integer literal 0x3333333333333333 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x3333333333333400 is the nearest value that can be represented exactly.
    const m2 = 0x3333333333333333;
               ^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:33:16: Error: The integer literal 0x0F0F0F0F0F0F0F0F can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0xf0f0f0f0f0f0f00 is the nearest value that can be represented exactly.
    const m4 = 0x0F0F0F0F0F0F0F0F;
               ^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:34:16: Error: The integer literal 0x00FF00FF00FF00FF can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0xff00ff00ff0100 is the nearest value that can be represented exactly.
    const m8 = 0x00FF00FF00FF00FF;
               ^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:36:17: Error: The integer literal 0x0101010101010101 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x101010101010100 is the nearest value that can be represented exactly.
    const h01 = 0x0101010101010101;
                ^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:75:30: Error: The operator '>>' isn't defined for the class 'num'.
Try correcting the operator to an existing operator, or defining a '>>' operator.
      bitCount += ((x * h01) >> 56);
                             ^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:75:16: Error: A value of type 'num' can't be assigned to a variable of type 'int'.
      bitCount += ((x * h01) >> 56);
               ^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:151:24: Error: The integer literal 0x03f79d71b4cb0a89 can't be represented exactly in JavaScript.
Try changing the literal to something that can be represented in Javascript. In Javascript 0x3f79d71b4cb0a80 is the nearest value that can be represented exactly.
    const debruijn64 = 0x03f79d71b4cb0a89;
                       ^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/git/antlr4-f0d4d129b7f146c314101bd3c99e630dc433af50/runtime/Dart/lib/src/util/bit_set.dart:152:58: Error: The operator '>>' isn't defined for the class 'num'.
Try correcting the operator to an existing operator, or defining a '>>' operator.
    return index64[(((value ^ (value - 1)) * debruijn64) >> 58) % 64];
                                                         ^^
Failed to compile application.
```

Maybe this requires only a small fix by using `BigInt` in `bit_set.dart`.

### PR DESCRIPTION
**Pull request by ansiemens**
fixes #3190 

Support Dart multiple platforms. 

- Uses conditional import / export on `dart:io`.
- Defines 32bit version bit set operations as JS version does not operate on 64bit integers.
- Migrates from `dart2native` to `dart compile exe`.
- Runs `dartfmt` on Dart runtime.

### CODE REVIEW

File: runtime/Dart/lib/src/error/error.dart [hunk 1]
```diff
@@ -4,6 +4,9 @@
  * can be found in the LICENSE.txt file in the project root.
  */
 
+export 'src/console_error_listener_stub.dart'
+    if (dart.library.io) 'src/console_error_listener_io.dart'
+    if (dart.library.html) 'src/console_error_listener_html.dart';
```
Comment (lingyv-li) [inline runtime/Dart/lib/src/error/error.dart:9]: Instead of making the whole console error listener, I prefer extracting just the `stderr.writeln` method like what you did in other places.

**Review by lingyv-li — CHANGES_REQUESTED** [review]
Overall it looks pretty good! 👍  
You also need to remove this import, potentially with a hack:
https://github.com/antlr/antlr4/blob/37393343ba22344a7d73ee90a7e46ae63bd90adb/tool/resources/org/antlr/v4/tool/templates/codegen/Dart/Dart.stg#L62

This is how I would do it:
https://github.com/lingyv-li/antlr4/commit/2843096cabbb5138ffef3749e71512bc770036cb#diff-6e09474b1421fd5d94035b5b34836896dbf8534f6e7b65cb860590c36b314aabR2


Also since you've removed the `locateDart2native` already, can you please also remove `locatePub`?
https://github.com/antlr/antlr4/blob/a0b5c93debf504427f7d00b6f1efe9a953c4db56/runtime-testsuite/test/org/antlr/v4/test/runtime/dart/BaseDartTest.java#L317

File: runtime/Dart/lib/src/error/error.dart (hunk 1 above)
Comment (ansiemens) [reply runtime/Dart/lib/src/error/error.dart]: Thanks for the suggestion. Updated.

File: runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Dart.test.stg [hunk 2]
```diff
@@ -269,7 +269,7 @@ LRListener(X) ::= <<
 class LeafListener extends TBaseListener {
   void exitE(EContext ctx) {
     if (ctx.childCount==3) {
-      stdout.write("${ctx.e(0)?.start?.text} ${ctx.e(1)?.start?.text} ${ctx.es()[0].start?.text}\n");
+      print("${ctx.e(0)?.start?.text} ${ctx.e(1)?.start?.text} ${ctx.es()[0].start?.text}");
```
Comment (itai42) [inline runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Dart.test.stg:272]: shouldn't this also be TEST_platformStdoutWrite?

Comment (ansiemens) [reply runtime-testsuite/resources/org/antlr/v4/test/runtime/templates/Dart.test.stg:272]: This line had a newline add the end. The change is to replace the 'write' with 'writeln' (print).

**Review by lingyv-li — CHANGES_REQUESTED** [review]
Also, can you show a working demo of it on web? Would be good to show it working against e.g. Java 9 grammar https://github.com/antlr/grammars-v4/tree/master/java/java9

File: runtime/Dart/lib/src/util/platform_html.dart [hunk 3]
```diff
@@ -0,0 +1,11 @@
+import 'dart:html';
+
```
[the remark this answers is not in the document]
Comment (ansiemens) [reply runtime/Dart/lib/src/util/platform_html.dart:2]: Updated.

File: runtime/Dart/CHANGELOG.md [hunk 4]
```diff
@@ -2,3 +2,7 @@
 ## 4.9.0
 
 * Initial release
+
+## 4.9.3-SNAPSHOT
+
+* Support multi-platform.
```
Comment (lingyv-li) [inline runtime/Dart/CHANGELOG.md:8]: This file needs to follow semantic versioning. Change it to 4.9.3 so it will be used when publishing that version.

Also it's better described as "Support web platform" since it already support other native platforms before this version.

```suggestion
## 4.9.3

* Support web platform.
```

**Review by lingyv-li — CHANGES_REQUESTED** [review]
Hey @ansiemens sorry it wasn't clear, and the Java grammar is a little tricky to work with. Don't worry I just tried and built a demo app from your branch for Java, it works great!

https://user-images.githubusercontent.com/8937944/129039312-94c7d86f-0547-4fa6-a9ad-c3185776c810.mov

https://github.com/lingyv-li/java9parser/tree/cc6318a0e3072ff2651fa704f2ff4cf331519ffc


Please remove the example folder that you've just added.

**Comment by ansiemens** [comment]
Cool! Updated the PR. PTAL.

**Review by lingyv-li — APPROVED** [review]
LGTM! Thanks @ansiemens 
@ericvergnaud can you pls check & merge this PR

**Comment by ansiemens** [comment]
cc @parrt

**Comment by cesarParra** [comment]
This seems to not be working anymore when using the latest version of ANTLR4 (4.11.1).

Here's a portion of a diff when running it through 4.9.3 (left) vs. 4.11.1 (right).

image

**Comment by KvanTTT** [comment]
The change doesn't relate to the issue. Could you please elaborate on encountered errors?

**Comment by parrt** [comment]
@cesarParra perhaps you could start a new issue with a sample grammar and input that causes the problem.
